name: Run SUSHI init and Push Changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-sushi-init:
    if: "!contains(github.event.head_commit.message, 'Automated update: SUSHI-generated files')" # 👈 Previene loop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run SUSHI init
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            ghcr.io/bonfhir/ig-toolbox \
            sushi init

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git diff --quiet && git diff --cached --quiet || git commit -m "Automated update: SUSHI-generated files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

